### ISSUE TITLE
Sandisk 4gb

### ISSUE THREAD

**Issue by Ccecil** [adamgreen/SDCard#4]
Cleanup from previous test run.
Dumping SD CID register contents.
  CID = 0x03 0x53 0x44 0x53 0x55 0x30 0x34 0x47 0x80 0x0C 0x41 0x7F 0x1F 0x00 0xE3 0xF1
          Manufacturer ID: 0x03
                   OEM ID: SD
             Product Name: SU04G
         Product Revision: 8.0
    Product Serial Number: 0x0C417F1F
       Manufacturing Date: March 2014
                 Checksum: 0x78
Dumping SD OCR register contents.
  OCR = 0xC0FF8000
          Card Power Up Status: 1
          Card Capacity Status: 1
            UHS-II Card Status: 0
    Switching to 1.8V Accepted: 0
                    2.7 - 2.8V: 1
                    2.8 - 2.9V: 1
                    2.9 - 3.0V: 1
                    3.0 - 3.1V: 1
                    3.1 - 3.2V: 1
                    3.2 - 3.3V: 1
                    3.3 - 3.4V: 1
                    3.4 - 3.5V: 1
                    3.5 - 3.6V: 1
Dumping SD CSD register contents.
  CSD = 0x40 0x0E 0x00 0x32 0x5B 0x59 0x00 0x00 0x1D 0x8A 0x7F 0x80 0x0A 0x40 0x40 0xB9
    CSD Version: 2.0
                  Data Read Access-Time: 0x0E (1ms)
    Data Read Access-Time in CLK cycles: 0
                      Max Transfer Rate: 25.0MHz
                  Card Command Class  0: yes
                  Card Command Class  1: no
                  Card Command Class  2: yes
                  Card Command Class  3: no
                  Card Command Class  4: yes
                  Card Command Class  5: yes
                  Card Command Class  6: no
                  Card Command Class  7: yes
                  Card Command Class  8: yes
                  Card Command Class  9: no
                  Card Command Class 10: yes
                  Card Command Class 11: no
             Max Read Data Block Length: 512
        Partial Blocks for Read Allowed: no
               Write Block Misalignment: no
                Read Block Misalignment: no
                        DSR Implemented: no
                            Device Size: 3965190144 bytes
              Erase Single Block Enable: 512 bytes
        Erase Sector Size (SECTOR_SIZE): 128
               Write Protect Group Size: 0
             Write Protect Group Enable: no
                     Write Speed Factor: 4
            Max Write Data Block Length: 512
       Partial Blocks for Write Allowed: no
                      File Format Group: 0
                              Copy Flag: copy
             Permanent Write Protection: 0
             Temporary Write Protection: 0
                            File Format: 0
                                    CRC: 0x5C
Performing write test of 10485760 bytes...
    1.77 MB/second.
Performing read test of 10485760 bytes...
    1.64 MB/second.
Validating data on disk.
Validated 10485760 bytes.
Removing test file.
SD Card Driver Counters
    selectFirstExchangeRequiredCount = 1280
    maximumWaitWhileBusyTime = 54
    maximumWaitForR1ResponseLoopCount = 2
    maximumACMD41LoopTime = 22
    cmd12PaddingByteRequiredCount = 1280
Test Completed!

**Comment by adamgreen** [comment]
Moved successful run to issue #1
