### ISSUE TITLE
Adata 8gb

### ISSUE THREAD

**Issue by Ccecil** [adamgreen/SDCard#5]
Cleanup from previous test run.
Dumping SD CID register contents.
  CID = 0x1D 0x41 0x44 0x53 0x44 0x20 0x20 0x20 0x02 0xB6 0x58 0x64 0x1E 0x00 0xF2 0xAD
          Manufacturer ID: 0x1D
                   OEM ID: AD
             Product Name: SD
         Product Revision: 0.2
    Product Serial Number: 0xB658641E
       Manufacturing Date: February 2015
                 Checksum: 0x56
Dumping SD OCR register contents.
  OCR = 0xC0FF8000
          Card Power Up Status: 1
          Card Capacity Status: 1
            UHS-II Card Status: 0
    Switching to 1.8V Accepted: 0
                    2.7 - 2.8V: 1
                    2.8 - 2.9V: 1
                    2.9 - 3.0V: 1
                    3.0 - 3.1V: 1
                    3.1 - 3.2V: 1
                    3.2 - 3.3V: 1
                    3.3 - 3.4V: 1
                    3.4 - 3.5V: 1
                    3.5 - 3.6V: 1
Dumping SD CSD register contents.
  CSD = 0x40 0x0E 0x00 0x32 0x5B 0x59 0x00 0x00 0x3A 0xDD 0x7F 0x80 0x0A 0x40 0x00 0xA9
    CSD Version: 2.0
                  Data Read Access-Time: 0x0E (1ms)
    Data Read Access-Time in CLK cycles: 0
                      Max Transfer Rate: 25.0MHz
                  Card Command Class  0: yes
                  Card Command Class  1: no
                  Card Command Class  2: yes
                  Card Command Class  3: no
                  Card Command Class  4: yes
                  Card Command Class  5: yes
                  Card Command Class  6: no
                  Card Command Class  7: yes
                  Card Command Class  8: yes
                  Card Command Class  9: no
                  Card Command Class 10: yes
                  Card Command Class 11: no
             Max Read Data Block Length: 512
        Partial Blocks for Read Allowed: no
               Write Block Misalignment: no
                Read Block Misalignment: no
                        DSR Implemented: no
                            Device Size: 7901020160 bytes
              Erase Single Block Enable: 512 bytes
        Erase Sector Size (SECTOR_SIZE): 128
               Write Protect Group Size: 0
             Write Protect Group Enable: no
                     Write Speed Factor: 4
            Max Write Data Block Length: 512
       Partial Blocks for Write Allowed: no
                      File Format Group: 0
                              Copy Flag: original
             Permanent Write Protection: 0
             Temporary Write Protection: 0
                            File Format: 0
                                    CRC: 0x54
Performing write test of 10485760 bytes...
    1.74 MB/second.
Performing read test of 10485760 bytes...
    1.66 MB/second.
Validating data on disk.
Validated 10485760 bytes.
Removing test file.
SD Card Driver Counters
    maximumWaitWhileBusyTime = 15
    maximumWaitForR1ResponseLoopCount = 1
    maximumACMD41LoopTime = 1
    maximumReceiveDataBlockWaitTime = 1
    cmd12PaddingByteRequiredCount = 1246
Test Completed!

**Comment by adamgreen** [comment]
Moved to issue #1
