### ISSUE TITLE
Kingston 2gb

### ISSUE THREAD

**Issue by Ccecil** [adamgreen/SDCard#6]
Cleanup from previous test run.
Dumping SD CID register contents.
  CID = 0x02 0x54 0x4D 0x53 0x44 0x30 0x32 0x47 0x38 0xA8 0xC1 0xFD 0x97 0x00 0x89 0xAF
          Manufacturer ID: 0x02
                   OEM ID: TM
             Product Name: SD02G
         Product Revision: 3.8
    Product Serial Number: 0xA8C1FD97
       Manufacturing Date: September 2008
                 Checksum: 0x57
Dumping SD OCR register contents.
  OCR = 0x80FF8000
          Card Power Up Status: 1
          Card Capacity Status: 0
            UHS-II Card Status: 0
    Switching to 1.8V Accepted: 0
                    2.7 - 2.8V: 1
                    2.8 - 2.9V: 1
                    2.9 - 3.0V: 1
                    3.0 - 3.1V: 1
                    3.1 - 3.2V: 1
                    3.2 - 3.3V: 1
                    3.3 - 3.4V: 1
                    3.4 - 3.5V: 1
                    3.5 - 3.6V: 1
Dumping SD CSD register contents.
  CSD = 0x00 0x2E 0x00 0x32 0x5B 0x5A 0x83 0xA9 0xFF 0xFF 0xFF 0x80 0x16 0x80 0x00 0x91
    CSD Version: 1.0
                  Data Read Access-Time: 2.0 ms
    Data Read Access-Time in CLK cycles: 0
                      Max Transfer Rate: 25.0MHz
                  Card Command Class  0: yes
                  Card Command Class  1: no
                  Card Command Class  2: yes
                  Card Command Class  3: no
                  Card Command Class  4: yes
                  Card Command Class  5: yes
                  Card Command Class  6: no
                  Card Command Class  7: yes
                  Card Command Class  8: yes
                  Card Command Class  9: no
                  Card Command Class 10: yes
                  Card Command Class 11: no
             Max Read Data Block Length: 1024
        Partial Blocks for Read Allowed: yes
               Write Block Misalignment: no
                Read Block Misalignment: no
                        DSR Implemented: no
                            Device Size: 3752 (1967128576 bytes)
             Max Read Current @ VDD min: 100.00 mA
             Max Read Current @ VDD max: 200.00 mA
            Max Write Current @ VDD min: 100.00 mA
            Max Write Current @ VDD max: 200.00 mA
                 Device Size Multiplier: 512
              Erase Single Block Enable: 512 bytes
        Erase Sector Size (SECTOR_SIZE): 128
               Write Protect Group Size: 1
             Write Protect Group Enable: no
                     Write Speed Factor: 32
            Max Write Data Block Length: 1024
       Partial Blocks for Write Allowed: no
                      File Format Group: 0
                              Copy Flag: original
             Permanent Write Protection: 0
             Temporary Write Protection: 0
                            File Format: 0
                                    CRC: 0x48
Performing write test of 10485760 bytes...
    1.59 MB/second.
Performing read test of 10485760 bytes...
    1.64 MB/second.
Validating data on disk.
Validated 10485760 bytes.
Removing test file.
SD Card Driver Counters
    maximumWaitWhileBusyTime = 174
    maximumWaitForR1ResponseLoopCount = 2
    maximumACMD41LoopTime = 62
    cmd12PaddingByteRequiredCount = 1278
Test Completed!

**Comment by adamgreen** [comment]
Moved to issue #1
