### ISSUE TITLE
Sandisk 1gb

### ISSUE THREAD

**Issue by Ccecil** [adamgreen/SDCard#7]
Cleanup from previous test run.
Dumping SD CID register contents.
  CID = 0x03 0x53 0x44 0x53 0x55 0x30 0x31 0x47 0x80 0x10 0xCA 0x87 0x23 0x00 0x71 0x01
          Manufacturer ID: 0x03
                   OEM ID: SD
             Product Name: SU01G
         Product Revision: 8.0
    Product Serial Number: 0x10CA8723
       Manufacturing Date: January 2007
                 Checksum: 0x00
Dumping SD OCR register contents.
  OCR = 0x80FF8000
          Card Power Up Status: 1
          Card Capacity Status: 0
            UHS-II Card Status: 0
    Switching to 1.8V Accepted: 0
                    2.7 - 2.8V: 1
                    2.8 - 2.9V: 1
                    2.9 - 3.0V: 1
                    3.0 - 3.1V: 1
                    3.1 - 3.2V: 1
                    3.2 - 3.3V: 1
                    3.3 - 3.4V: 1
                    3.4 - 3.5V: 1
                    3.5 - 3.6V: 1
Dumping SD CSD register contents.
  CSD = 0x00 0x26 0x00 0x32 0x5F 0x59 0x83 0xC8 0xBE 0xFB 0xCF 0xFF 0x92 0x40 0x40 0xD7
    CSD Version: 1.0
                  Data Read Access-Time: 1.5 ms
    Data Read Access-Time in CLK cycles: 0
                      Max Transfer Rate: 25.0MHz
                  Card Command Class  0: yes
                  Card Command Class  1: no
                  Card Command Class  2: yes
                  Card Command Class  3: no
                  Card Command Class  4: yes
                  Card Command Class  5: yes
                  Card Command Class  6: yes
                  Card Command Class  7: yes
                  Card Command Class  8: yes
                  Card Command Class  9: no
                  Card Command Class 10: yes
                  Card Command Class 11: no
             Max Read Data Block Length: 512
        Partial Blocks for Read Allowed: yes
               Write Block Misalignment: no
                Read Block Misalignment: no
                        DSR Implemented: no
                            Device Size: 3875 (1015808000 bytes)
             Max Read Current @ VDD min: 100.00 mA
             Max Read Current @ VDD max: 80.00 mA
            Max Write Current @ VDD min: 100.00 mA
            Max Write Current @ VDD max: 80.00 mA
                 Device Size Multiplier: 512
              Erase Single Block Enable: 512 bytes
        Erase Sector Size (SECTOR_SIZE): 32
               Write Protect Group Size: 128
             Write Protect Group Enable: yes
                     Write Speed Factor: 16
            Max Write Data Block Length: 512
       Partial Blocks for Write Allowed: no
                      File Format Group: 0
                              Copy Flag: copy
             Permanent Write Protection: 0
             Temporary Write Protection: 0
                            File Format: 0
                                    CRC: 0x6B
Performing write test of 10485760 bytes...
    1.76 MB/second.
Performing read test of 10485760 bytes...
    1.64 MB/second.
Validating data on disk.
Validated 10485760 bytes.
Removing test file.
SD Card Driver Counters
    selectFirstExchangeRequiredCount = 1280
    maximumWaitWhileBusyTime = 76
    maximumWaitForR1ResponseLoopCount = 2
    maximumACMD41LoopTime = 3
    maximumReceiveDataBlockWaitTime = 1
    cmd12PaddingByteRequiredCount = 1280
Test Completed!

**Comment by adamgreen** [comment]
Moved to issue #1
